### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Yumekawa-chan** [qinglew/PCN#28]
After completing the train, we can run
python test.py --exp_name PCN_16384 --ckpt_path checkpoint/best_l1_cd.pth --batch_size 32 --num_workers 8
After executing
FileNotFoundError: [Errno 2] No such file or directory: '/data/PCN/test.list'.
I got an error "FileNotFoundError: [Errno 2] No such file or directory: '/data/PCN/test.list'.
Can someone please help me?

**Comment by Ting234** [comment]
Maybe you should download PCN.zip and extract to the data/PCN

**Comment by Kir1s4me** [comment]
> After completing the train, we can run python test.py --exp_name PCN_16384 --ckpt_path checkpoint/best_l1_cd.pth --batch_size 32 --num_workers 8 After executing FileNotFoundError: [Errno 2] No such file or directory: '/data/PCN/test.list'. I got an error "FileNotFoundError: [Errno 2] No such file or directory: '/data/PCN/test.list'. Can someone please help me?

I have the same problem，have you solved it？

**Comment by Hannes9** [comment]
I have the same problem. Would really appreciate it if anyone solved it or has a solution to this.

Thanks !

**Comment by MarioCavero** [comment]
> After completing the train, we can run python test.py --exp_name PCN_16384 --ckpt_path checkpoint/best_l1_cd.pth --batch_size 32 --num_workers 8 After executing FileNotFoundError: [Errno 2] No such file or directory: '/data/PCN/test.list'. I got an error "FileNotFoundError: [Errno 2] No such file or directory: '/data/PCN/test.list'. Can someone please help me?

The files should exist inside the PCN downloadable dataset! Both train and test.list files contain the data. 
```
~/Downloads/PCN$ ls train/partial/
02691156  02933112  02958343  03001627  03636649  04256520  04379243  04530566
~/Downloads/PCN$ ls train/complete/
02691156  02933112  02958343  03001627  03636649  04256520  04379243  04530566
~/Downloads/PCN$ ls test/
complete/ partial/  
~/Downloads/PCN$ ls test/partial/
02691156  02933112  02958343  03001627  03636649  04256520  04379243  04530566
~/Downloads/PCN$ ls test/complete/
02691156  02933112  02958343  03001627  03636649  04256520  04379243  04530566
```
These correspond to the elements in the files. For example, for the specific object with the id `04530566`, which is the Boat or Vessel. 
```
:~/Downloads/PCN$ cat train.list | grep 04530566 | head
04530566/786f18c5f99f7006b1d1509c24a9f631
04530566/df0f90c6abbfeaa0255deca950ace5f9
04530566/6a541c64083d2bb9c5408f4f799fe72
04530566/eca25540e280ac1c2d1e53cffa2132f6
04530566/ca2e4bd483c006a5c9f3294669fff77d
04530566/955507bbb3aa0b97b1bb46d2556ba67d
04530566/3c785a132fbf152249d508bbe117085
04530566/f1800fb3a9873af1e64f09105f9c8a56
04530566/355f5aa01c79fe1458a8952c93ff9829
04530566/7d7fe630419cb3e3ff217e1345ac0f8
~/Downloads/PCN$ cat test.list | grep 04530566 | head
04530566/176c629c93b5a1f73cf0b8b75857cc24
04530566/8ff4c7162259b1d5cf816caaec167fbf
04530566/93304640e3a2a60d611cd70ef25f5235
04530566/2ceb5d34a15b73393302308333adc4be
04530566/263eeac4bcfca21285f7a3de54751f1b
04530566/8f9e62cf323515c4ca380c8375c4cdb6
04530566/41d1856d2e24a738b4624ce09086ad45
04530566/5456c7546e3f3c3d9c5408f4f799fe72
04530566/283dc6c755398547657a96a9bceb8713
04530566/587793fcbae6a6fbf5abe4b4be4c3d4b
```
From the different objects inside: dataset/shapenet.py:
```
        # self.cat2id = {
        #     # seen categories
        #     "airplane"  : "02691156",  # plane
        #     "cabinet"   : "02933112",  # dresser
        #     "car"       : "02958343",
        #     "chair"     : "03001627",
        #     "lamp"      : "03636649",
        #     "sofa"      : "04256520",
        #     "table"     : "04379243",
        #     "vessel"    : "04530566",  # boat
            
        #     # alis for some seen categories
        #     "boat"      : "04530566",  # vessel
        #     "couch"     : "04256520",  # sofa
        #     "dresser"   : "02933112",  # cabinet
        #     "airplane"  : "02691156",  # airplane
        #     "watercraft": "04530566",  # boat

        #     # unseen categories
        #     "bus"       : "02924116",
        #     "bed"       : "02818832",
        #     "bookshelf" : "02871439",
        #     "bench"     : "02828884",
        #     "guitar"    : "03467517",
        #     "motorbike" : "03790512",
        #     "skateboard": "04225987",
        #     "pistol"    : "03948459",
        # }
```

If you used your own dataset, then you should create those files while or after the creation of the dataset and its folder structure! 
In simmple words, something like:
```
Boat/Boat1
Boat/Boat2
```
I hope it helps! @Yumekawa-chan  @Kir1s4me

**Comment by Yumekawa-chan** [comment]
Thank you!

**Comment by Hannes9** [comment]
@MarioCavero Can you recommend any tool/workflow/code which is automazing the separation of complete and partial data to its folders and renaming partial data respectively ? I would be interested e.g. how the files & folders were set up for the given PCN example dataset on Google Drive with such a big amount of data automized. 
E.g. how I have organized my dataset initially: all complete data in one folder & all the partial data in one folder. All filenames are the GUID of the objects.

Thanks a lot !
